# -*- coding: utf-8 -*-
"""code for pkl to jpg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cVTO2GhhGwFC-o55XQOm0HFnueRHPYx9
"""

import pickle
import matplotlib.pyplot as plt
import numpy as np
import time

data = pickle.load(open("/content/457511-7.pck",'rb'))
print(data.shape)

for i,d in enumerate(data):
    #img = np.reshape(d,(320,320,1))
    #print(d.shape)
    plt.imshow(d)
    plt.axis('off')
    plt.savefig('img'+str(i)+'.jpg')
    plt.show()

